language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"

services:
  - docker

before_install:
  - docker run -d -p 127.0.0.1:27017:27017 mongo

install:
  - npm install

script:
  - npm run ci
