version: "3"
services:

  res-server:
    build: .
    image: res-server:lates
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db-data:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
